server:
  port: ${APP_PORT:8082}
spring:
  application:
    name: Demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_HOST:localhost}:${DB_PG_PORT:5432}/${DB_PG_BASE:demo}?prepareThreshold=0
    username: ${DB_PG_USR_RW:postgres}
    password: ${DB_PG_PWD_RW:postgres}
    hikari:
      maximum-pool-size: ${DB_PG_POOL_SIZE:20}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
